In [2]:
import warnings
warnings.filterwarnings('ignore')

In [9]:
import numpy as np
import random

In [10]:
a = np.arange(1, 46)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]


In [40]:
np.random.seed(85)
lotto = []
np.random.shuffle(a)
a = a[:7]
for i in range(6):
    lotto.append(a[i])
print('lotto = ', lotto)

lotto =  [17, 28, 15, 34, 16, 30]


In [58]:
lotto.sort()
a = np.arange(1, 46)
np.random.shuffle(a)
b = a[7]
print('lotto = ', lotto, '추가번호 = ', b)

lotto =  [15, 16, 17, 28, 30, 34] 추가번호 =  6


In [61]:
c = np.array(range(25)).reshape((5, 5))
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [68]:
print('첫 원소 : ', c[0][0])
print('마지막 원소 : ', c[-1][-1])

첫 원소 :  0
마지막 원소 :  24


In [73]:
print(c[0:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [122]:
print(c[:5, ::2])

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]]


In [129]:
print(c[:2].reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [133]:
d = np.random.rand(8).reshape(2, 2, 2)
print(d)

[[[0.63067933 0.16943521]
  [0.90335719 0.92792879]]

 [[0.39771109 0.50749807]
  [0.18503364 0.2933868 ]]]


In [170]:
import math
# k = max(map(max, d))
#  d.argmax()
d = d.reshape(1, 8)
d = max(d[:7])
print(' d 배열의 최대값 : ', max(d))

 d 배열의 최대값 :  0.9279287883462869
