In [3]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
import numpy as np

a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [6]:
print(a)

[2 3 4]


In [7]:
a.shape

(3,)

In [9]:
a.ndim

1

In [10]:
a.dtype

dtype('int32')

In [11]:
a.itemsize

4

In [12]:
a.size

3

In [13]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b.shape

(2, 3)

In [14]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.full((2, 3), 100)

array([[100, 100, 100],
       [100, 100, 100]])

In [18]:
np.eye(3) #단위행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
b = np.array([1, 1])

In [20]:
k = np.eye(4)

In [21]:
k = k * 10

In [22]:
k

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])

In [23]:
print(np.linspace(0, np.pi, 10))

[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]


In [26]:
j = np.linspace(0, np.pi, 11)

In [27]:
print(np.sin(j))

[0.00000000e+00 3.09016994e-01 5.87785252e-01 8.09016994e-01
 9.51056516e-01 1.00000000e+00 9.51056516e-01 8.09016994e-01
 5.87785252e-01 3.09016994e-01 1.22464680e-16]


In [28]:
b = np.array([[1, 1], [2, 2], [3, 3]])

In [31]:
np.insert(b, 1, [1, 2, 3], axis = 1)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])