In [2]:
import warnings
warnings.filterwarnings(action='ignore')

In [4]:
import numpy as np

x = np.arange(10).reshape(5, 2)
print(x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [6]:
x = np.arange(10).reshape(-1, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
x = np.arange(10).reshape(5, -1)
print(x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [8]:
x = np.arange(10).reshape(-1)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
y = np.arange(1, 10).reshape(3, 3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
z = np.full((3, 3), 3)
print(z)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [17]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [18]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
print('\n')

In [20]:
print(a[:, 1:])

[[2 3]
 [5 6]
 [8 9]]


In [21]:
print('\n')

In [22]:
print(a[0:1, 0:2])

[[1 2]]


In [23]:
t = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])

In [25]:
print(t)
print('\n')
print(t[::2, ::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


[[ 1  3  5]
 [11 13 15]]


In [26]:
import time

In [27]:
n = 1000
arr = np.random.rand(n, n)

In [28]:
sum_naive = 0
start = time.time()
for i in range(n):
    for j in range(n):
        sum_naive += arr[i, j]
end = time.time()

print(n, 'x', n, '배열의 원소 합', sum_naive, '\n계산 시간: ', end-start)

1000 x 1000 배열의 원소 합 500261.00365462824 
계산 시간:  0.18304133415222168


In [29]:
start = time.time()
sum_reduction = np.sum(arr, axis = (0, 1))
end = time.time()

print(n, 'x', n, '배열의 원소 합', sum_reduction, '\n계산 시간: ', end-start)

1000 x 1000 배열의 원소 합 500261.00365463924 
계산 시간:  0.0020003318786621094
