In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

print(arr)
print(arr[1:3])
print(arr[:-1])
print(arr[::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [4]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

print(arr)
print(arr[:, 1:3])
print(arr[:, :-1])
print(arr[:, ::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [5]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

print(arr)
print(arr[1:3, :-1])
print(arr[2:, 1:3])
print(arr[::2, ::2])
print(arr[1::2, 1::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 5  6  7]
 [ 9 10 11]]
[[10 11]
 [14 15]]
[[ 1  3]
 [ 9 11]]
[[ 6  8]
 [14 16]]


In [6]:
array1 = np.array([1, 2, 3, 4]).reshape(2, 2)
array2 = np.array([1.5, 2.5])

add = array1 + array2

print(add)

[[2.5 4.5]
 [4.5 6.5]]
